### PR TITLE
Adds compatibility for some mods

### PR DESCRIPTION
**Pull request by Sweet-Defender-Turtle**
This should add compatibility to the following mods:

- Barn and Coop by Lu_B17
- Cute and Tidy Coops and Barns by neuralwiles
- Lnh's Leisure Barn by LiuNianHui
- Lnh's Leisure Coop by LiuNianHui

I also wanted to create compatibility for Jen's Mega Coop and Barn but can't figure how to get it to target the right location (the mod adds new buildings instead of overriding the way the barn and coop look) so I'd love to get some help with that!

### CODE REVIEW

**Comment by gzhynko** [comment]
Hey! First of all, huge thanks for the work, really appreciate it! 

I decided to rework the profiles once again (hopefully for the last time) to support custom buildings. That means that the system will require a new format for the json files, but this will hopefully add a way to add profiles for mods like  Jen's Mega Coop and Barn. Just started working on it though, so it'll probably take some time to finish, but once it's done I'll circle back to this thread!

**Comment by Sweet-Defender-Turtle** [comment]
It's no problem at all! I actually kinda enjoyed it!

I wish you a lot of luck with reworking the profiles and will be looking forward to hearing from you when you're done!!

**Comment by gzhynko** [comment]
Alright, the changes should be up now, please take a look at the new format for profiles - essentially, the items in "placement" must be in the same order as the building names in "targetBuilding" so that they correspond to each other. The building names themselves are the names of the building indoor maps, so, for example, from taking a quick look at Jen's Mega Coop and Barn, the name of the map for the coop should be "Coop4".

Please let me know if you have any questions about the format or if you see any bugs, as I haven't had much time to test it out yet.

**Comment by Sweet-Defender-Turtle** [comment]
okay so I've updated the files I already had and have added:

- Jen's Mega Coop and Barn
- Resource Chickens by UncleArya (adds a new upgrade for the Coop)
- Walk of Life - Rebirth by DaLion (the Yieldmaster profession adds +2 capacity to both the coop and barn when chosen)

I've unfortunately not been able to test whether or not it works since I'm not able to download animals need water in a way for me to be able to run it.

If it's possible to upload the file in a way that I would be able to I'm more than willing to test things out!

**Comment by gzhynko** [comment]
Thanks! Here's a build with the new profile system: 
[AnimalsNeedWater 1.6.0.zip](https://github.com/user-attachments/files/16712424/AnimalsNeedWater.1.6.0.zip)
This doesn't include the new profiles, but it should pick them up if you put them in the assets/TroughPlacementProfiles folder.
Let me know if anything comes up during testing!

**Comment by Sweet-Defender-Turtle** [comment]
Okay so I've tested everything and it seems to work! I've come across no errors or warnings during my testing. Finding the map names was actually the hardest part (thank the gods for LookUp Anything and Debug Mode)! 

I've double checked all the files I've made (as well as Cuter Coops and Better Barns) to make sure there weren't any out of place sprites or maps not loading. In theory the mod should be good to go!

**Comment by gzhynko** [comment]
Awesome, then I'll merge the PR and push the update to Nexus. Huge thanks again for the help, mod compatibility is always a tricky thing to manage with this mod, so I really appreciate your work!

**Comment by Sweet-Defender-Turtle** [comment]
Glad I was able to help! I quite enjoy doing these kinds of things so if I end up finding anything that could use some compatibility (either due to requests in comments or for personal enjoyment) I end up making em.

If you ever need help with some more compatibility stuff I'd be happy to help!!

**Pull request merged**
